// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MindfulWebAPI.Models;

#nullable disable

namespace MindfulWebAPI.Migrations
{
    [DbContext(typeof(MindfulDbContext))]
    partial class MindfulDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MindfulWebAPI.Models.AffirmationEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AffirmationEntries", t =>
                        {
                            t.HasCheckConstraint("CK_AffirmationEntry_Category_MinLength", "LEN(Category) >= 4");

                            t.HasCheckConstraint("CK_AffirmationEntry_Text_MinLength", "LEN(Text) >= 4");
                        });
                });

            modelBuilder.Entity("MindfulWebAPI.Models.MeditationSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MeditationSessions", t =>
                        {
                            t.HasCheckConstraint("CK_MeditationSession_DurationMinutes_Range", "DurationMinutes >= 1 AND DurationMinutes <= 600");
                        });
                });

            modelBuilder.Entity("MindfulWebAPI.Models.MoodEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mood")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MoodEntries", t =>
                        {
                            t.HasCheckConstraint("CK_MoodEntry_Mood_MinLength", "LEN(Mood) >= 3");

                            t.HasCheckConstraint("CK_MoodEntry_Note_MinLength", "LEN(Note) >= 4");
                        });
                });

            modelBuilder.Entity("MindfulWebAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FullName")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_User_Email_MinLength", "LEN(Email) >= 4");

                            t.HasCheckConstraint("CK_User_FullName_MinLength", "LEN(FullName) >= 4");

                            t.HasCheckConstraint("CK_User_Location_MinLength", "LEN(Location) >= 4 OR Location IS NULL");

                            t.HasCheckConstraint("CK_User_Password_MinLength", "LEN(Password) >= 4");

                            t.HasCheckConstraint("CK_User_Phone_ExactLength", "LEN(Phone) = 10");

                            t.HasCheckConstraint("CK_Users_Email_Valid", "[Email] LIKE '%_@_%._%' AND LEN([Email]) <= 254 AND [Email] NOT LIKE '%[^a-zA-Z0-9@._]%' AND [Email] NOT LIKE '%@%@%' AND [Email] NOT LIKE '%.@%' AND [Email] NOT LIKE '%@.%' AND [Email] NOT LIKE '%.' AND [Email] NOT LIKE '@%' AND [Email] NOT LIKE '.%'");
                        });
                });

            modelBuilder.Entity("MindfulWebAPI.Models.AffirmationEntry", b =>
                {
                    b.HasOne("MindfulWebAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MindfulWebAPI.Models.MeditationSession", b =>
                {
                    b.HasOne("MindfulWebAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MindfulWebAPI.Models.MoodEntry", b =>
                {
                    b.HasOne("MindfulWebAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
